import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/ui/Footer";

export const metadata = {
  title: "Terms of Service — VeraCius AI",
};

// §9.3 — a plain-language draft, not legal advice. Have it reviewed before
// relying on it for a real deployment.

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-display text-lg font-bold text-foreground mb-2">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-graphite-bg">
      <Navbar />
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-display text-3xl md:text-4xl font-black text-foreground mb-2">Terms of Service</h1>
        <p className="text-xs text-muted-foreground font-mono mb-10">
          Draft — informational only, not legal advice. Have this reviewed by counsel before relying on it for a public launch.
        </p>

        <Section title="What this service is">
          <p>
            VeraCius AI is an automated research aid that generates AI-produced assessments of factual claims. See
            the <a href="/methodology" className="text-neonRed hover:underline">Methodology &amp; Limitations</a> page
            for how it works and what it cannot do.
          </p>
        </Section>

        <Section title="No warranty of accuracy">
          <p>
            Verdicts, confidence scores, and explanations are generated by AI systems and can be incomplete, outdated,
            or wrong. Nothing on this site constitutes professional, legal, medical, or financial advice, and nothing
            here should be the sole basis for a consequential decision.
          </p>
        </Section>

        <Section title="Acceptable use">
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>Don't use automated tools to bypass rate limits or extract data at scale.</li>
            <li>Don't submit content whose sole purpose is to attack, harass, or defame a private individual.</li>
            <li>Don't attempt to use the scraping endpoints to reach internal or non-public network resources.</li>
            <li>Don't misrepresent an AI-generated verdict as an authoritative, human fact-check.</li>
          </ul>
        </Section>

        <Section title="Accounts">
          <p>
            You're responsible for the accuracy of the account information you provide and for activity under your
            account. You may delete your account at any time from your profile page.
          </p>
        </Section>

        <Section title="Changes">
          <p>These terms may be updated as the product evolves; continued use after a change constitutes acceptance of the updated terms.</p>
        </Section>
      </main>
      <Footer />
    </div>
  );
}
