"use client";

import { motion } from "framer-motion";
import { ShieldAlert, ShieldCheck, AlertTriangle, ShieldQuestion, XOctagon, Share2, Download, Copy } from "lucide-react";

interface IntelligenceReportProps {
  verdict: "VERIFIED" | "PARTIALLY VERIFIED" | "MISLEADING" | "UNVERIFIED" | "FALSE";
  confidenceScore: number;
  summary: string;
  keyFindings: string[];
}

export default function IntelligenceReport({ verdict, confidenceScore, summary, keyFindings }: IntelligenceReportProps) {
  const getVerdictConfig = (v: string) => {
    switch (v) {
      case "VERIFIED":
        return { color: "text-verificator-verified", bg: "bg-verificator-verified/10", border: "border-verificator-verified/50", icon: ShieldCheck };
      case "PARTIALLY VERIFIED":
        return { color: "text-verificator-mostlyTrue", bg: "bg-verificator-mostlyTrue/10", border: "border-verificator-mostlyTrue/50", icon: ShieldAlert };
      case "MISLEADING":
        return { color: "text-verificator-mixture", bg: "bg-verificator-mixture/10", border: "border-verificator-mixture/50", icon: AlertTriangle };
      case "UNVERIFIED":
        return { color: "text-verificator-unverifiable", bg: "bg-verificator-unverifiable/10", border: "border-verificator-unverifiable/50", icon: ShieldQuestion };
      case "FALSE":
        return { color: "text-verificator-false", bg: "bg-verificator-false/10", border: "border-verificator-false/50", icon: XOctagon };
      default:
        return { color: "text-muted-foreground", bg: "bg-[#241014]", border: "border-graphite-border-sec", icon: ShieldQuestion };
    }
  };

  const config = getVerdictConfig(verdict);
  const Icon = config.icon;

  return (
    <div className="w-full bg-graphite-bg border border-graphite-border rounded-2xl overflow-hidden relative">
      {/* Header */}
      <div className={`p-6 border-b border-graphite-border flex flex-col md:flex-row md:items-center justify-between gap-6 relative`}>
        {/* Subtle background glow based on verdict */}
        <div className={`absolute inset-0 ${config.bg} opacity-20 pointer-events-none`} />
        
        <div className="flex items-center gap-4 relative z-10">
          <div className={`w-14 h-14 rounded-2xl ${config.bg} border ${config.border} flex items-center justify-center`}>
            <Icon className={`w-7 h-7 ${config.color}`} />
          </div>
          <div>
            <h2 className="font-mono text-xs text-muted-foreground uppercase tracking-widest mb-1">
              INTELLIGENCE ASSESSMENT
            </h2>
            <h3 className={`font-display text-3xl font-black tracking-wide ${config.color}`}>
              {verdict}
            </h3>
          </div>
        </div>

        <div className="relative z-10 flex flex-col items-end">
          <span className="font-mono text-[10px] text-muted-foreground tracking-widest mb-1 uppercase">
            CONFIDENCE METRIC
          </span>
          <div className={`font-mono text-4xl font-bold ${config.color}`}>
            {confidenceScore}%
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="p-6 md:p-8 space-y-8">
        <div>
          <h4 className="font-mono text-xs text-neonRed uppercase tracking-widest mb-3 flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-neonRed" />
            EXECUTIVE SUMMARY
          </h4>
          <p className="text-foreground leading-relaxed text-sm">
            {summary}
          </p>
        </div>

        <div>
          <h4 className="font-mono text-xs text-neonRed uppercase tracking-widest mb-4 flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-neonRed" />
            KEY FINDINGS
          </h4>
          <div className="space-y-3">
            {keyFindings.map((finding, idx) => (
              <div key={idx} className="flex gap-3 items-start p-4 rounded-xl bg-graphite-surface border border-graphite-border">
                <span className="font-mono text-xs text-muted-foreground mt-0.5">{(idx + 1).toString().padStart(2, '0')}</span>
                <p className="text-sm text-muted-foreground leading-relaxed">{finding}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Footer Actions */}
      <div className="p-4 border-t border-graphite-border bg-graphite-surface flex items-center justify-between">
        <div className="font-mono text-[10px] text-muted-foreground flex items-center gap-2 uppercase tracking-widest">
          <div className="w-1.5 h-1.5 rounded-full bg-neonRed animate-pulse" />
          REPORT GENERATED BY VERACIUS AI
        </div>
        <div className="flex gap-2">
          <button className="p-2 rounded-lg bg-graphite-bg border border-graphite-border text-muted-foreground hover:text-neonRed hover:border-neonRed/50 transition-colors">
            <Copy className="w-4 h-4" />
          </button>
          <button className="p-2 rounded-lg bg-graphite-bg border border-graphite-border text-muted-foreground hover:text-neonRed hover:border-neonRed/50 transition-colors">
            <Download className="w-4 h-4" />
          </button>
          <button className="p-2 rounded-lg bg-graphite-bg border border-graphite-border text-muted-foreground hover:text-neonRed hover:border-neonRed/50 transition-colors">
            <Share2 className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
